hls-bitrate=max
profile = high-quality
keep-open = yes
save-position-on-quit = yes
hr-seek-framedrop=no
no-resume-playback

#Video
vo = gpu-next 
gpu-api = vulkan
hwdec = auto

#Audio
volume = 70
volume-max = 100
audio-pitch-correction=yes  

#Ram 
cache=yes 
demuxer-max-back-bytes = 20M  
demuxer-max-bytes = 20M 

#OSD
osc = no
osd-bar = no
border = no
