general {
	  lock_cmd = pidof hyprlock || hyprlock
	  before_sleep_cmd = if [[ "$(playerctl status)" == "Playing" ]]; then playerctl play-pause; fi
	  after_sleep_cmd = if [[ "$(playerctl status)" == "Paused" ]]; then playerctl play-pause; fi
    ignore_dbus_inhibit = false             # whether to ignore dbus-sent idle-inhibit requests (used by e.g. firefox or steam)
}
listener {
    timeout = 300                           # in seconds
    on-timeout = pidof hyprlock || hyprlock
}
