#source = ~/.config/hypr/hyprland/main.conf
#source = ~/.config/hypr/hyprland/env.conf
#source = ~/.config/hypr/hyprland/keybinds.conf
#source = ~/.config/hypr/hyprland/exec.conf
#source = ~/.config/hypr/hyprland/rules.conf
#source = ~/.config/hypr/hyprland/plugin.conf
#Source all config files in the hyprland folder
source = ~/.config/hypr/hyprland/*

