#Authentication
exec-once = xhost + local:
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
#Clipboard : History
exec-once = wl-paste --watch cliphist store
exec-once = wl-clip-persist --clipboard regular
#Notifications 
exec-once = mako
#Idle
exec-once = hypridle
#Search Engine
#exec-once = searxng-run
#exec-once = fcitx5 -d
#exec-once=hyprpaper
#exec-once=hyprpm reload
