#Window Rules for Hyprland
windowrule = workspace 1 silent,firefox
windowrule = workspace 2 silent,vesktop
windowrule = workspace 3 silent,steam

windowrulev2 = float,class:(clipse) # ensure you have a floating window class set if you want this behaviour
windowrulev2 = size 622 652,class:(clipse) # set the size of the window as necessary
