[files]
recent_files=/home/fern/Downloads/RSPM/RSPM !readme!.rtf;/home/fern/Downloads/data/base.rnp;/home/fern/Downloads/data/readme.txt;/home/fern/Downloads/Robot Nanny/babs/bonus0.bab;/home/fern/Downloads/Robot Nanny/babs/bab0.bab;/home/fern/Downloads/Robot Nanny/babs/bab1.bab;/home/fern/Downloads/Robot Nanny/babs/bab2.bab;/home/fern/Downloads/Robot Nanny/babs/bablist.txt;/home/fern/Downloads/Robot Nanny/babs/bab6.bab;/home/fern/.local/share/wavey-launcher/debug.log;
recent_projects=
current_page=0

[project]
session_file=
project_file_path=/home/roki/projects

[geany]
treeview_position=156
msgwindow_position=387
geometry=0;0;960;1054;1;
sidebar_page=1

[search]
find_all_expanded=true
replace_all_expanded=false
position_find_x=0
position_find_y=0
position_replace_x=0
position_replace_y=0
position_fif_x=-1
position_fif_y=-1

[plugins]
load_plugins=true
custom_plugin_path=
active_plugins=;

[VTE]
last_dir=/home/ven
