[files]
recent_files=/home/fern/.config/waybar/style.css;/home/fern/Downloads/Champion_of_Venus_Taylas_Big_Adventure_v0.3-linux/CoV_Tayla-0.3-linux/CoV_Tayla.sh;/home/fern/data/.hidden;/home/fern/Stash/codes;/home/fern/.mozilla/firefox/yt19zcgr.fern/chrome/userChrome.css;/home/fern/dotfiles/.config/yt-dlp/config;/home/fern/Stash/Music/users.txt;/home/fern/Downloads/music.txt;/home/fern/Stash/Music/music.txt;/home/fern/Downloads/memtest86-usb/readme.txt;
recent_projects=
current_page=1
FILE_NAME_0=11;None;0;EUTF-8;1;1;0;%2Fhome%2Ffern%2Fdata%2F.hidden;0;4
FILE_NAME_1=65;CSS;0;EUTF-8;1;1;0;%2Fhome%2Ffern%2F.config%2Fwaybar%2Fstyle.css;0;4

[project]
session_file=
project_file_path=/home/roki/projects

[geany]
treeview_position=156
msgwindow_position=387
geometry=0;0;484;526;1;
sidebar_page=1

[search]
find_all_expanded=true
replace_all_expanded=false
position_find_x=0
position_find_y=0
position_replace_x=0
position_replace_y=0
position_fif_x=-1
position_fif_y=-1

[plugins]
load_plugins=true
custom_plugin_path=
active_plugins=;

[VTE]
last_dir=/home/ven
