profile=gpu-hq
gpu-api=vulkan
osc=no
osd-bar=no
ytdl-format=bestvideo[height<=?1080]+bestaudio/best # Set max streaming quality as 1080p.
volume=100 # Set volume to 100% on startup.
volume-max=100 # Set player max vol to 100%
